# Generated by Django 5.1.6 on 2025-02-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
