# Generated by Django 5.1.6 on 2025-02-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_mpesatransaction_payment_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
