# Generated by Django 5.2 on 2025-04-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FF', 'Frames'), ('WT', 'Wheels'), ('BS', 'Brakes'), ('HC', 'Handlebars'), ('SG', 'Gears'), ('BC', 'Bicycles'), ('SC', 'Suspension'), ('EC', 'Electricals'), ('DC', 'Drivetrain')], max_length=2),
        ),
    ]
