# Generated by Django 5.2 on 2025-04-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_order_shipping_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='total_cost',
        ),
    ]
