# Generated by Django 5.2 on 2025-04-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_total_amount_order_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_cost',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
    ]
